### ISSUE TITLE
Server.py for chapter-1 gives the fallowing error in windows 10 and vs code sanic version is  sanic-22.3.0 websockets-10.2

### ISSUE THREAD

**Issue by Facimus** [PacktPublishing/Web-Development-with-Sanic#10]
```
PS Z:\Sanic> & C:/Users/KK/AppData/Local/Microsoft/WindowsApps/python3.10.exe z:/Sanic/server.py
[2022-04-16 19:23:40 +0300] [14792] [INFO] 
  ┌─────────────────────────────────────────────────────────────┐
  │                        Sanic v22.3.0                        │
  │              Goin' Fast @ http://127.0.0.1:9999             │
  ├───────────────────────┬─────────────────────────────────────┤
  │                       │     mode: debug, single worker      │
  │     ▄███ █████ ██     │   server: sanic                     │
  │    ██                 │   python: 3.10.4                    │
  │     ▀███████ ███▄     │ platform: Windows-10-10.0.19044-SP0 │
  │                 ██    │ packages: sanic-routing==22.3.0     │
  │    ████ ████████▀     │                                     │
  │                       │                                     │
  │ Build Fast. Run Fast. │                                     │
  └───────────────────────┴─────────────────────────────────────┘

[2022-04-16 19:23:40 +0300] [14792] [DEBUG] Dispatching signal: server.init.before
[2022-04-16 19:23:40 +0300] [14792] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\mixins\runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\server\runners.py", line 146, in serve
    ctrlc_workaround_for_windows(app)
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\compat.py", line 91, in ctrlc_workaround_for_windows    
    app.add_task(stay_active)
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\app.py", line 1217, in add_task
    loop = self.loop  # Will raise SanicError if loop is not started
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\app.py", line 255, in loop
    return get_running_loop()
RuntimeError: no running event loop
Traceback (most recent call last):
  File "z:\Sanic\server.py", line 13, in <module>
    app.run(port=9999, debug=True)
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-pacckges\sanic\mixins\runner.py", line 145, in run
ages\sanic\mixins\runner.py", line 145, in run
    self.__class__.serve(primary=self)  # type: ignore                                                                                   c
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-pa  File "z:\Sanic\server.py", line 13, in <module>
    app.run(port=9999, debug=True)                                                                                                       c
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\mixins\runner.py", line 145, in run
    self.__class__.serve(primary=self)  # type: ignore                                                                                   c
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\mixins\runner.py", line 578, in serve
    serve_single(primary_server_info.settings)                                                                                           c
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)                                                                                                             c
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\server\runners.py", line 146, in serve
    ctrlc_workaround_for_windows(app)                                                                                                    c
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\compat.py", line 91, in ctrlc_workaround_for_windows
    app.add_task(stay_active)
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\app.py", line 1217, in add_task
    loop = self.loop  # Will raise SanicError if loop is not started
  File "C:\Users\KK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sanic\app.py", line 255, in loop
    return get_running_loop()
RuntimeError: no running event loop
PS Z:\Sanic>
```

**Comment by ahopkins** [comment]
Thank you for reporting this. The book examples were all validated with Sanic 21.12, which is the current Long Term Support release. They should definitely work if you use:

```
pip install sanic==21.12
```

However, with that said there is a fix for Windows support with v22 that I should be releasing some time today.

**Comment by ahopkins** [comment]
For reference: https://github.com/sanic-org/sanic/pull/2421

**Comment by ahopkins** [comment]
I just released v22.3.1 which should resolve this issue. I would love to hear your feedback to know if it resolves the issue for you.

**Comment by Facimus** [comment]
Works with  v22.3.1
Thank you.

**Comment by ahopkins** [comment]
Thank you @Facimus for the feedback.
