### ISSUE TITLE
Chapter11 - Error on starting application

### ISSUE THREAD

**Issue by fanchlegal** [PacktPublishing/Web-Development-with-Sanic#12]
Hi,

I launch the application with command : docker-compose up in the Chapter11 directory and I got this error :

app_1          | wait-for-it: db-postgres:5432 is available after 0 seconds
app_1          | wait-for-it: waiting 15 seconds for db-redis:6379
app_1          | wait-for-it: db-redis:6379 is available after 0 seconds
app_1          | /usr/local/lib/python3.10/site-packages/sanic_jwt/configuration.py:134: DeprecationWarning: There is no current event loop
app_1          |   if asyncio.get_event_loop().is_running():
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/lib/python3.10/site-packages/sanic/cli/app.py", line 146, in _get_app
app_1          |     app = app(self.args)
app_1          |   File "/app/booktracker/server.py", line 47, in create_app
app_1          |     setup_modules(app, *module_names)
app_1          | TypeError: Value after * must be an iterable, not Namespace
app_1          | 
app_1          | During handling of the above exception, another exception occurred:
app_1          | 
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/bin/sanic", line 8, in <module>
app_1          |     sys.exit(main())
app_1          |   File "/usr/local/lib/python3.10/site-packages/sanic/__main__.py", line 12, in main
app_1          |     cli.run()
app_1          |   File "/usr/local/lib/python3.10/site-packages/sanic/cli/app.py", line 85, in run
app_1          |     app = self._get_app()
app_1          |   File "/usr/local/lib/python3.10/site-packages/sanic/cli/app.py", line 148, in _get_app
app_1          |     app = app()
app_1          |   File "/app/booktracker/server.py", line 36, in create_app
app_1          |     app = Sanic("BooktrackerApp", request_class=BooktrackerRequest)
app_1          |   File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 223, in __init__
app_1          |     self.__class__.register_app(self)
app_1          |   File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 1461, in register_app
app_1          |     raise SanicException(f'Sanic app name "{name}" already in use.')
app_1          | sanic.exceptions.SanicException: Sanic app name "BooktrackerApp" already in use.
booktracker_app_1 exited with code 1

Can you help me ?
Thanks

**Comment by ahopkins** [comment]
@fanchlegal Yes, I will check shortly. Just curious, which version of Sanic are you trying with?

**Comment by fanchlegal** [comment]
@ahopkins Yes this is my version : Sanic 22.6.2; Routing 22.3.0

**Comment by ahopkins** [comment]
:thinking: The code in Chapter 11 should be all within a docker container, running v21.12. Can you let me know how you ran the commands?

**Comment by fanchlegal** [comment]
I just launch docker-compose up in the directory

Le lun. 19 sept. 2022 à 18:20, Adam Hopkins ***@***.***> a
écrit :

**Comment by ahopkins** [comment]
@fanchlegal I see the problem. The code was written for v21.12, but the requirements.txt are not pinned for that. In a recent version of Sanic, we inject arguments into the factory pattern.

See https://sanic.dev/en/guide/release-notes/v22.3.html#cli-arguments-optionally-injected-into-application-factory

This is breaking the pattern. I will get a code fix pushed to the repository. In the mean time you could pin the version in `requirements.txt` to `sanic==21.12`.

Thanks for bringing this to my attention.

**Comment by fanchlegal** [comment]
@ahopkins : i change the version in the requirements.txt file and now i got this error :

 Starting in v22.3, --debug will no longer automatically run the auto-reloader.
booktracker-app-1          |   Switch to --dev to continue using that functionality.
booktracker-app-1          | /usr/local/lib/python3.10/site-packages/sanic_jwt/configuration.py:134: DeprecationWarning: There is no current event loop
booktracker-app-1          |   if asyncio.get_event_loop().is_running():
booktracker-app-1          | Traceback (most recent call last):
booktracker-app-1          |   File "/usr/local/bin/sanic", line 8, in <module>
booktracker-app-1          |     sys.exit(main())
booktracker-app-1          |   File "/usr/local/lib/python3.10/site-packages/sanic/__main__.py", line 12, in main
booktracker-app-1          |     cli.run()
booktracker-app-1          |   File "/usr/local/lib/python3.10/site-packages/sanic/cli/app.py", line 75, in run
booktracker-app-1          |     app = self._get_app()
booktracker-app-1          |   File "/usr/local/lib/python3.10/site-packages/sanic/cli/app.py", line 147, in _get_app
booktracker-app-1          |     raise e
booktracker-app-1          |   File "/usr/local/lib/python3.10/site-packages/sanic/cli/app.py", line 130, in _get_app
booktracker-app-1          |     app = app()
booktracker-app-1          |   File "/app/booktracker/server.py", line 47, in create_app
booktracker-app-1          |     setup_modules(app, *module_names)
booktracker-app-1          |   File "/app/booktracker/worker/module.py", line 11, in setup_modules
booktracker-app-1          |     module = import_module(module_name)
booktracker-app-1          |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
booktracker-app-1          |     return _bootstrap._gcd_import(name[level:], package, level)
booktracker-app-1          |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
booktracker-app-1          |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
booktracker-app-1          |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
booktracker-app-1          |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
booktracker-app-1          |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
booktracker-app-1          |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
booktracker-app-1          |   File "/app/booktracker/blueprints/view.py", line 3, in <module>
booktracker-app-1          |     from .author.view import bp as author_bp
booktracker-app-1          |   File "/app/booktracker/blueprints/author/view.py", line 7, in <module>
booktracker-app-1          |     from sanic_ext import validate
booktracker-app-1          |   File "/usr/local/lib/python3.10/site-packages/sanic_ext/__init__.py", line 3, in <module>
booktracker-app-1          |     from sanic_ext.bootstrap import Extend
booktracker-app-1          |   File "/usr/local/lib/python3.10/site-packages/sanic_ext/bootstrap.py", line 14, in <module>
booktracker-app-1          |     from sanic_ext.extensions.http.extension import HTTPExtension
booktracker-app-1          |   File "/usr/local/lib/python3.10/site-packages/sanic_ext/extensions/http/extension.py", line 4, in <module>
booktracker-app-1          |     from .methods import add_auto_handlers, add_http_methods
booktracker-app-1          |   File "/usr/local/lib/python3.10/site-packages/sanic_ext/extensions/http/methods.py", line 12, in <module>
booktracker-app-1          |     from ..openapi import openapi
booktracker-app-1          |   File "/usr/local/lib/python3.10/site-packages/sanic_ext/extensions/openapi/openapi.py", line 25, in <module>
booktracker-app-1          |     from sanic_ext.extensions.openapi import definitions
booktracker-app-1          |   File "/usr/local/lib/python3.10/site-packages/sanic_ext/extensions/openapi/definitions.py", line 23, in <module>
booktracker-app-1          |     from .types import Definition, Schema
booktracker-app-1          |   File "/usr/local/lib/python3.10/site-packages/sanic_ext/extensions/openapi/types.py", line 17, in <module>
booktracker-app-1          |     from sanic_routing.patterns import nonemptystr
booktracker-app-1          | ImportError: cannot import name 'nonemptystr' from 'sanic_routing.patterns' (/usr/local/lib/python3.10/site-packages/sanic_routing/patterns.py)
